### ISSUE TITLE
Update the attribute name to 'attribute_levenshtein'

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_levensthein#1]
see at https://en.wikipedia.org/wiki/Levenshtein_distance

``` diff
- attribute_levensthein
+ attribute_levenshtein
```

**Comment by discordier** [comment]
OMFG... TYPO IN THE REPO NAME!!!!!! We are all gonna DIEEEEEEEE!!!!!!!1111 :bomb: :smile: 

Ok, we should change this.

**Comment by discordier** [comment]
I wonder how we can make the transition in repository name (github name, URL, packagist) seamless.

I currently see multiple culprits that might arise, I guess we have to abandon the original on packagist and add it anew.

**Comment by zonky2** [comment]
I would open a new package - maybe at MM 2.2 and here's a hint about the move

**Comment by zonky2** [comment]
foxed in MM 2.2 `attribute_levenshtein`
