### ISSUE TITLE
Minimale Wortlänge lässt sich nicht erhöhen, ist nach dem Speichern 0

### ISSUE THREAD

**Issue by Ainschy** [MetaModels/attribute_levensthein#12]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_levensthein/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 7.x         |                                  |
| Contao version:                     |   4.4.45       |                                  |
| MetaModels version:                 |   2.1.1       |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |   all + levensthein       |                                  |

## Issue description

Minimale (deutsche Übersetzung Maximale ...) Wortlänge ist immer 0, Wert lässt sich nicht erhöhen.

**Comment by zonky2** [comment]
wird schon alles richtig gespeichert... nur der MCW-Optionlistener macht Mist...
Values kommen schon so an - es werden die ArrayKeys 0, 1, 2... ausgegeben
https://github.com/MetaModels/attribute_levensthein/blob/42889b2e84c2d0310d29873b7c05f65be8ae645e/src/EventListener/DcGeneral/Table/Attribute/LoadDistancesListener.php#L44-L50
```
array:3 [▼
  0 => array:2 [▼
    "wordLength" => "2"
    "distance" => "2"
  ]
  1 => array:2 [▼
    "wordLength" => "4"
    "distance" => "2"
  ]
  2 => array:2 [▼
    "wordLength" => "6"
    "distance" => "2"
  ]
]
```
sehen nach dem Umwandeln so aus 
```
array:3 [▼
  0 => array:2 [▼
    "wordLength" => 0
    "distance" => array:2 [▼
      "wordLength" => "2"
      "distance" => "2"
    ]
  ]
  1 => array:2 [▼
    "wordLength" => 1
    "distance" => array:2 [▶]
  ]
  2 => array:2 [▼
    "wordLength" => 2
    "distance" => array:2 [▶]
  ]
]
```
würde vereinfachen
```diff
-        $processed = [];

-        foreach ((array) $event->getValue() as $wordLength => $distance) {
-            $processed[] = ['wordLength' => $wordLength, 'distance' => $distance];
-        }

-        $event->setValue(serialize($processed));
+        $event->setValue(serialize((array) $event->getValue()));
```

@discordier btw: wieso ist da ein MCW für mehrere Eingaben angelegt? verstehe ich nicht...

**Comment by zonky2** [comment]
fixed https://github.com/MetaModels/attribute_levensthein/pull/14

**Comment by discordier** [comment]
Fixed in 105b946
