### ISSUE TITLE
No results when typing searchword with a capital letter

### ISSUE THREAD

**Issue by m-r-h-n** [MetaModels/attribute_levensthein#3]
While typing a searchword on a mobile device the first letter is capital by default. At least on my device.
In tl_metamodel_levensthein_index words are stored in lowercase. 
In that case mentioned above no results are found - if i type in some searchphrase in lowercase results are shown.

I played around a bit with the LevenstheinAjax.php and changed row 72
from:
`&& ($search = $input->get('search'))`
to:
`&& ($search = utf8_strtolower($input->get('search')))`

That solved it for me…
I´m not a native programmer but maybe this can be solved with it.
Thanks for your effort on this by the way!

**Comment by richardhj** [comment]
Just figured out by testing:
The search is case-insensitive, however, the ajax-results are not.

**Comment by discordier** [comment]
@richardhj so where exactly is the problem then? In the ajax provider?
Can you either point me to the correct location or even better fix the problem right away?

**Comment by richardhj** [comment]
I think we should tackle it in the `SearchStringParser`.
When fetching the suggestion, `$omitLastToken` is `true` and the partial token gets not lowercased as it would be within the `handleToken()` method.
See https://github.com/richardhj/metamodels-attribute_levensthein/commit/ceb5b7e6ac39513ff208c3099c60acea806e77b2. (Sorry for no PR, my base branch is broken.)

**Comment by discordier** [comment]
I still do not get why it has to be lowercased. I mean, in the `handleToken()` all passed chunks are also not lowercased.

**Comment by richardhj** [comment]
But they get lowercased after passed to `handleToken()`

**Comment by discordier** [comment]
Ah, now I see, in `addLiteralToken`, `addMustNotToken`, `addMustToken` and `addKeywordToken`.

So yes, your solution seems to be correct.

**Comment by zonky2** [comment]
@discordier & @richardhj fixed or not?!?

**Comment by richardhj** [comment]
Not yet, this Commit needs to be picked https://github.com/richardhj/metamodels-attribute_levensthein/commit/ceb5b7e6ac39513ff208c3099c60acea806e77b2

Give me one second.

**Comment by zonky2** [comment]
Link => 404?
